version: "3"
services:

  postgres-mlflow:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mlflow-backend-store
    ports:
      - 5432:5432
    volumes:
      - ./mlflow/data:/var/lib/postgresql/data:z

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000  # S3 API port
      - 9001:9001  # web ui
    volumes:
      - ./mlflow/artifacts/data:/data:z
    command: server /data --console-address ":9001"

  mlflow:
    build:
      context: ./mlflow/server
    depend_on:
      - minio
      - postgres
    ports:
      - 5000:5000
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: uYZgyaQZPpSSCTBpJT3z
      AWS_SECRET_ACCESS_KEY: kgk4B3nFPTXrsjGZCRpF0B7Na8YXXywHXhCEjRRt
    command: [
      "mlflow",
      "server",
      "--backend-store-uri", "postgresql://postgres:postgres@postgres-mlflow/mlflow-backend-store",
      "--default-artifact-root", "s3://mlflow-artifacts",
      "--host", "0.0.0.0"
    ]
