services:
  jupyter:
    build:
      context: ./jupyter
    volumes:
      - ./jupyter/:/jupyter:z
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8888
    env_file:
      - ./jupyter/.env
    command: [
      "bash",
      "-c",
      "jupyter lab --ip=0.0.0.0 --port 8888  --allow-root --no-browser --notebook-dir=/jupyter"
    ]
