volumes:
  feast-postgres-data:

services:
  feast-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feast-database
    ports:
      - 5433:5432
    volumes:
      - feast-postgres-data:/var/lib/postgresql/data:z

  feast:
    build:
      context: ./feast
    ports:
      - 8889:8888
    volumes:
      - ./feast/repository:/repository:z
