version: "3"
services:

  postgres-feast:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feature-database
    ports:
      - 5433:5432
    volumes:
      - ./feast/data:/var/lib/postgresql/data:z

