version: "3"
services:
  server:
    build:
      context: .
    volumes:
      - ./:/jupyter:z
    ports:
      - 8888:8888
    env_file:
      - .env
    command: [
      "bash",
      "-c",
      "jupyter lab --ip=0.0.0.0 --port 8888  --allow-root --no-browser --notebook-dir=/jupyter"
    ]
