version: "3"

volumes:
  nexus-data:
  postgres-data-mlflow:
  minio-data:

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./data/.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data-mlflow:/var/lib/postgresql/data:z

  minio:
    image: minio/minio:latest
    env_file:
      - ./artifacts/.env
    ports:
      - 9000:9000  # S3 API port
      - 9001:9001  # web ui
    volumes:
      - minio-data:/data:z
      - ./artifacts/init-minio.sh:/init-minio.sh:z
      - ./artifacts/policy-list-buckets.json:/policy-list-buckets.json:z
    command: server /data --console-address ":9001"

  server:
    build:
      context: ./server
    depend_on:
      - minio
      - postgres
    ports:
      - 5000:5000
    env_file:
      - ./server/.env
    command: [
      "mlflow",
      "server",
      "--backend-store-uri", "postgresql://postgres:postgres@postgres-data-mlflow/mlflow-backend-store",
      "--default-artifact-root", "s3://mlflow-artifacts",
      "--host", "0.0.0.0"
    ]

  nexus:
    image: sonatype/nexus3
    ports:
      - 8081:8081  # web UI
      - 8082:8082  # docker-registry port
    volumes:
      - nexus-data:/nexus-data
      - ./registry/init-nexus.sh:/opt/sonatype/init-nexus.sh:z
